version: 2
jobs:
    gtest:
        working_directory: ~/root
        docker:
            - image: gcc:latest
        steps:
            - run:
                name: Downloading dependencies
                command: |
                    apt-get update
                    apt-get install -y cmake
                    apt-get install -y libgtest-dev
            - run:
                name: Installing dependencies
                working_directory: /usr/src/gtest/
                command: |
                    cmake CMakeLists.txt
                    make
                    cp /usr/src/gtest/*.a /usr/lib
            - checkout
            - run:
                name: Building tests
                command: make test
            - run:
                name: Running tests
                command: ./test.exe
    samples:
        working_directory: ~/root
        docker:
            - image: gcc:latest
        steps:
            - checkout
            - run:
                name: Building sample
                command: make example
            - run:
                name: Running sample
                command: ./example.exe
workflows:
    version: 2
    build_and_test:
        jobs:
            - gtest
            - samples
